theme: jekyll-theme-cayman
title: Domain-Independent Dynamic Programming (DIDP)
description: This is a homepage for Domain-Independent Dynamic Programming (DIDP).

plugins:
  - jekyll-sitemap

domain: domain-independent-dp.github.io
url: https://domain-independent-dp.github.io
baseurl: /
repository: domain-independent-dp/domain-independent-dp.github.io
